name: Unit Testing

env:
  GODOT_VERSION: 4.3
  TEST_PATH: res://Test
  
on:
  push:
    branches:  # Runs on every push to any branch
      - '**'
  pull_request:
    branches:  # Runs on every pull request to any branch
      - '**'
      
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MikeSchulze/gdunit4-action@v1.1.5
        with:
          godot-version: ${{ env.GODOT_VERSION }} 
          paths: ${{ env.TEST_PATH }}
          publish-report: false
