name: Updates the update log to new pushes

permissions:
  contents: write  

on:
  push:
    branches:
      - reset

jobs:
  append-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v3
        with:
          ref: reset
          fetch-depth: 0  
      - name: Check for merge conflicts in "What's been added.txt"
        id: conflict_check
        run: |
          if git ls-files -u | grep "Updates/What's been added.txt"; then
            echo "conflict=true" >> $GITHUB_ENV
          else
            echo "conflict=false" >> $GITHUB_ENV
          fi

      - name: Exit if no conflicts
        if: env.conflict == 'false'
        run: echo "No conflicts detected. Exiting..." && exit 0

      - name: Check if log file exists
        run: |
          touch updates_log.txt  # Create if it doesn't exist

      - name: Append new updates to the log file
        run: |
          export TZ=Asia/Manila
          echo "---- Update from latest push ($(date)) ----" >> updates_log.txt
          cat "Updates/What's been added.txt" >> updates_log.txt
          echo "" >> updates_log.txt  # Add newline for formatting

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f updates_log.txt
          git commit -m "Updated update log"
          git push origin reset
